### ISSUE TITLE
piwik-feedannotation breaks Piwik

### ISSUE THREAD

**Issue by linuxundich** [halfdan/piwik-feedannotation-plugin#15] opened 2014-03-16 03:05 UTC
I checked the latest source out of the git and activated the plugin. But unfortunately this breaks my piwik installation. I get this error message

The following error just broke Piwik (v2.1.0):

Call to undefined function Piwik\Plugins\FeedAnnotation\Piwik_AddAdminSubMenu()
in
/var/www/piwik.linuxandi.net/plugins/FeedAnnotation/FeedAnnotation.php line 66

**Comment by chrisspiegl** [comment] 2014-03-17 23:15
This is because it is currently not ready for 2.1 and the market place but there are already issues regarding those problems ( #14 #9 #13)

**Comment by halfdan** [comment] 2014-03-29 18:29
Closing this as a duplicate of above mentioned tickets. I'll need to clear some time this week to work on those.

**Closed as completed by halfdan** 2014-03-29 18:29 UTC
