### ISSUE TITLE
Dropdown site selection does not show the correct site

### ISSUE THREAD

**Issue by chrisspiegl** [halfdan/piwik-feedannotation-plugin#2] opened 2013-03-17 20:17 UTC
I tried to use this but I noticed the following:
- Switch to the FeedAnnotation Settings
- Select a site in the dropdown
- The site reloads and the dropdown shows the top most site in the list (not the one I just tried to select)

**Comment by Putr** [comment] 2013-03-17 21:30
I can confirm this (happens to me as well)
Piwik 1.11.1

**Comment by jthingelstad** [comment] 2013-03-18 01:36
The dropdown also is pretty janky if you have a lot of sites in Piwik. It would be nice if it did the same search stuff that Piwik itself does when you have a lot of sites.
![screenshot](https://f.cloud.github.com/assets/5351/268933/30f5cd72-8f6c-11e2-8cc7-21ee4e034462.png)

**Comment by halfdan** [comment] 2013-03-20 10:18
Thanks for the report, this is fixed in master now.

I'll keep the ticket open because @thingles issue. Will tackle it later today.

**Comment by halfdan** [comment] 2013-03-24 15:46
@thingles, this will have to be fixed upstream. There's currently no way to restrict this (for view access it is implemented, but I require admin access for which it is not).

Hopefully this will be possible with the 1.12 release.

**Comment by jthingelstad** [comment] 2013-03-25 01:46
Thanks for looking into it @halfdan!

**Closed as not planned** 2022-10-13 20:32 UTC
